import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import Navigation from '@/app/components/navigations/page'
const WorkSans = Work_Sans({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Lendsqr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={WorkSans.className}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
